name: CI

on: [pull_request]

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - run: pnpm run build
      - run: pnpm run typecheck
      - run: pnpm run test
